### ISSUE TITLE
Individual trait editing seems broken.

### ISSUE THREAD

**Issue by Rostislavmat** [Lithane97/Divine-Intervention#1]
When trying to add individual trait, there is no effect.
Based on error log, seem to be not resolving scope:trait

[21:35:33][jomini_script_system.cpp:276]: Script system error!
  Error: add_trait effect [ Cannot find scope:trait in trait database ]
  Script location: file: common/scripted_guis/DI_misc_sgui.txt line: 90
  
  Confirmed that that's what's happening by hardcoding add_trait to existing trait inside DI_add_trait (game successfully adds/removes hardcoded trait).

**Comment by Lithane97** [comment]
When is this happening? Mine works.

**Comment by Rostislavmat** [comment]
Game version : 1.9.0.2
Steps to reproduce: Load this mod only (source this repo, commit 3635cadaae5d06c684508d45c0222544509f9454), start new game (as any character), keep it un-paused. Open edit menu. choose any trait (e.g. "100 Stat Man") , left click it. Nothing seem to happen (trait does not appear, stats do not change). Same result if marking character and/or enabling "interaction on" beforehand.

Additional debug info:
Any other part of mod seems to work (including presets (adds all traits to char just fine) / skill editing / culture / etc).
During investigation, changed code for DI_add_trait (in order to debug whether this code path is being exercised) to: 

`DI_add_trait = {
	scope = character
	
	effect = {
		if = {
			limit = {
				has_global_variable = DI_marked_char_var
			}
			every_living_character = {
				limit = { has_character_flag = marked_for_edit }

				hidden_effect = {
                    **add_trait = 100_stat_man**
					add_trait = scope:trait
				}
			}
		}
		else = {
			hidden_effect = {
                **add_trait = 100_stat_man**
				add_trait = scope:trait
			}
		}
	}
}`

Upon reloading the mod, left-clicking any trait adds (both trait showing up + start getting set to 100) the "100 stat man" trait, which signals that this code path is being hit, but "add_trait = scope:trait" is not being processed correctly. 


I'm not super familiar with ck3 modding, so not sure, how I can add a log line to be written to error/message logs upon entering effect to provide more info.

**Comment by Lithane97** [comment]
Thanks for the info. You can use debug_log to send something to the debug log file. It takes scopes, so you could do debug_log = "Your text" 
or debug_log_scopes = yes 
to print scopes to the log.

**Comment by Rostislavmat** [comment]
1) Yep, DI_trait.gui looks exactly like this.
2) According to logs, the scope is:

[22:55:26][effectimpl.cpp:610]: Murchad Briain of d_munster (Internal ID: 17551 - Historical ID 83355) weak (Character - 17551)!
Root: Murchad Briain of d_munster (Internal ID: 17551 - Historical ID 83355) weak (Character - 17551)!

Saved event targets:
trait: temperate weak (Trait - 45)!

So it should be picking it up. According to [wiki](https://ck3.paradoxwikis.com/Interface), passed scope should be wrapped 
`"[ScriptedGui.Execute( GuiScope.SetRoot( GetPlayer.MakeScope ).AddScope('target', CharacterWindow.GetCharacter.MakeScope ).End )]"
And then we use the same name in the scripted gui:

saved_scope = {
  target
}`

Tested this potential solution, does not seem to work. 

3) Talked to chatGpt, after half an hour debugging session, we are our of ideas on what can be going wrong. Unless someone else reports this issue, I'd suggest closing it for the time being as it seems to be super specific.

Thanks for help, by the way!
